### ISSUE TITLE
Application to Join PaleCraft Staff

### ISSUE THREAD

**Issue by TheGoblinMilk** [PaleCraft/server#16]
We're always looking for help moderating the server!

Simply fill out the following form, **your answers will be posted publicly**, and we will review and get back to you with any questions ASAP!

**In Game Name:** 
GoblinMilk

**Age:** 
20 
            turning 21 on may 4th ^-^
**When did you first play minecraft?**
Since watersource blocks flooded the entire world, so. 9 years?

**Have you ever moderated an online community before?**
Yes, several.

**How long have you been active on the server?**
Like 2 months at this point.

**Tell us about your computer skills?**
Ive got above average computer skills I'd say?
pretty basic though. I can troubleshoot basic stuff. Find hidden files and the such.
Yeah.

**Comment by pale2hall** [comment]
:) 
Hellzyeah
